language: php

php:
    - 7.0

install:
    - composer self-update
    - composer require satooshi/php-coveralls
    - composer update

script:
    - phpenv config-rm xdebug.ini
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls
